version: "3.3"

volumes:
  static-admin-ui:
  static-market-ui:
  static-office-ui:
  static-signal-ui:


services:

  admin-api:
    container_name: admin-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    volumes:
      - static-admin-ui:/home/node/framework/services/admin-ui/dist/
    command: "npm run --prefix ./services/admin-api start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_ADMIN_API}"
      BUSINESS_TYPE: "${BUSINESS_TYPE}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_WS_URL: "${REDIS_WS_URL}"
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      REDIS_WATCHER_URL: "${REDIS_WATCHER_URL}"
      REDIS_CACHE_URL: "${REDIS_CACHE_URL}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_QUEUE_EMAIL: "${RMQ_QUEUE_EMAIL}"
      RMQ_QUEUE_CRON: "${RMQ_QUEUE_CRON}"
      RMQ_QUEUE_CORE_ETH: "${RMQ_QUEUE_CORE_ETH}"
      # FE
      ADMIN_FE_URL: "${ADMIN_FE_URL}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      GCLOUD_KEYFILE_BASE64_PATH: "${GCLOUD_KEYFILE_BASE64_PATH}"
      PRIVATE_KEY_SECRET_NAME: "${PRIVATE_KEY_SECRET_NAME}"
      # BLOCKCHAIN
      CHAIN_ID: "${CHAIN_ID}"
      ACCOUNT: "${ACCOUNT}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      JSON_RPC_ADDR: "${JSON_RPC_ADDR}"
      JSON_RPC_ADDR_ETHEREUM: "${JSON_RPC_ADDR_ETHEREUM}"
      JSON_RPC_ADDR_GOERLY: "${JSON_RPC_ADDR_GOERLY}"
      JSON_RPC_ADDR_BINANCE: "${JSON_RPC_ADDR_BINANCE}"
      JSON_RPC_ADDR_BINANCE_TEST: "${JSON_RPC_ADDR_BINANCE_TEST}"
      JSON_RPC_ADDR_POLYGON: "${JSON_RPC_ADDR_POLYGON}"
      JSON_RPC_ADDR_MUMBAI: "${JSON_RPC_ADDR_MUMBAI}"
      JSON_RPC_ADDR_BESU: "${JSON_RPC_ADDR_BESU}"
      JSON_RPC_ADDR_GEMUNION: "${JSON_RPC_ADDR_GEMUNION}"
      STARTING_BLOCK: "${STARTING_BLOCK}"
      # Contracts
      CONTRACT_MANAGER_ADDR: "${CONTRACT_MANAGER_ADDR}"
      EXCHANGE_ADDR: "${EXCHANGE_ADDR}"
      EXCHANGE_BINANCE_ADDR: "${EXCHANGE_BINANCE_ADDR}"
      DISPENSER_ADDR: "${DISPENSER_ADDR}"
      # DEV
      LINK_ADDR: "${LINK_ADDR}"
      VRF_ADDR: "${VRF_ADDR}"
    ports:
      # admin-api
      - "${PORT_ADMIN_API}:${PORT_ADMIN_API}"

  market-api:
    container_name: market-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    volumes:
      - static-market-ui:/home/node/framework/services/market-ui/dist/
    command: "npm run --prefix ./services/market-api start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_MARKET_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_WS_URL: "${REDIS_WS_URL}"
      RMQ_ADMIN_URL: "${RMQ_ADMIN_URL}"
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      REDIS_WATCHER_URL: "${REDIS_WATCHER_URL}"
      REDIS_CACHE_URL: "${REDIS_CACHE_URL}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_QUEUE_EMAIL: "${RMQ_QUEUE_EMAIL}"
      # FE
      MARKET_FE_URL: "${MARKET_FE_URL}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      GCLOUD_KEYFILE_BASE64_PATH: "${GCLOUD_KEYFILE_BASE64_PATH}"
      PRIVATE_KEY_SECRET_NAME: "${PRIVATE_KEY_SECRET_NAME}"
      # BLOCKCHAIN
      CHAIN_ID: "${CHAIN_ID}"
      ACCOUNT: "${ACCOUNT}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      JSON_RPC_ADDR: "${JSON_RPC_ADDR}"
      JSON_RPC_ADDR_ETHEREUM: "${JSON_RPC_ADDR_ETHEREUM}"
      JSON_RPC_ADDR_GOERLY: "${JSON_RPC_ADDR_GOERLY}"
      JSON_RPC_ADDR_BINANCE: "${JSON_RPC_ADDR_BINANCE}"
      JSON_RPC_ADDR_BINANCE_TEST: "${JSON_RPC_ADDR_BINANCE_TEST}"
      JSON_RPC_ADDR_POLYGON: "${JSON_RPC_ADDR_POLYGON}"
      JSON_RPC_ADDR_MUMBAI: "${JSON_RPC_ADDR_MUMBAI}"
      JSON_RPC_ADDR_BESU: "${JSON_RPC_ADDR_BESU}"
      JSON_RPC_ADDR_GEMUNION: "${JSON_RPC_ADDR_GEMUNION}"
      # Contracts
    ports:
      # market-api
      - "${PORT_MARKET_API}:${PORT_MARKET_API}"

  office-api:
    container_name: office-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    volumes:
      - static-office-ui:/home/node/framework/services/office-ui/dist/
    command: "npm run --prefix ./services/office-api start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_OFFICE_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_WS_URL: "${REDIS_WS_URL}"
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      REDIS_WATCHER_URL: "${REDIS_WATCHER_URL}"
      REDIS_CACHE_URL: "${REDIS_CACHE_URL}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_QUEUE_EMAIL: "${RMQ_QUEUE_EMAIL}"
      RMQ_QUEUE_CRON: "${RMQ_QUEUE_CRON}"
      RMQ_QUEUE_CORE_ETH: "${RMQ_QUEUE_CORE_ETH}"
      # FE
      OFFICE_FE_URL: "${OFFICE_FE_URL}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      GCLOUD_KEYFILE_BASE64_PATH: "${GCLOUD_KEYFILE_BASE64_PATH}"
      PRIVATE_KEY_SECRET_NAME: "${PRIVATE_KEY_SECRET_NAME}"
      # BLOCKCHAIN
      CHAIN_ID: "${CHAIN_ID}"
      ACCOUNT: "${ACCOUNT}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      JSON_RPC_ADDR: "${JSON_RPC_ADDR}"
      JSON_RPC_ADDR_ETHEREUM: "${JSON_RPC_ADDR_ETHEREUM}"
      JSON_RPC_ADDR_GOERLY: "${JSON_RPC_ADDR_GOERLY}"
      JSON_RPC_ADDR_BINANCE: "${JSON_RPC_ADDR_BINANCE}"
      JSON_RPC_ADDR_BINANCE_TEST: "${JSON_RPC_ADDR_BINANCE_TEST}"
      JSON_RPC_ADDR_POLYGON: "${JSON_RPC_ADDR_POLYGON}"
      JSON_RPC_ADDR_MUMBAI: "${JSON_RPC_ADDR_MUMBAI}"
      JSON_RPC_ADDR_BESU: "${JSON_RPC_ADDR_BESU}"
      JSON_RPC_ADDR_GEMUNION: "${JSON_RPC_ADDR_GEMUNION}"
      # Contracts
    ports:
      # office-api
      - "${PORT_OFFICE_API}:${PORT_OFFICE_API}"

  core-eth:
    container_name: core-eth
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./services/core-eth start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_RPC_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      GCLOUD_KEYFILE_BASE64_PATH: "${GCLOUD_KEYFILE_BASE64_PATH}"
      PRIVATE_KEY_SECRET_NAME: "${PRIVATE_KEY_SECRET_NAME}"
      # REDIS
      REDIS_WS_URL: "${REDIS_WS_URL}"
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      REDIS_WATCHER_URL: "${REDIS_WATCHER_URL}"
      REDIS_CACHE_URL: "${REDIS_CACHE_URL}"
      REDIS_QUEUE_NAME: "${REDIS_QUEUE_NAME_BESU}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_URL_MERCHANT: "${RMQ_URL_MERCHANT}"
      RMQ_QUEUE_EMAIL: "${RMQ_QUEUE_EMAIL}"
      RMQ_QUEUE_CORE_ETH: "${RMQ_QUEUE_CORE_ETH}"
      # FE
      FE_URL: "${ADMIN_FE_URL}"
      # LOGDNA
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      # BLOCKCHAIN
      CHAIN_ID: "${CHAIN_ID}"
      ACCOUNT: "${ACCOUNT}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      JSON_RPC_ADDR: "${JSON_RPC_ADDR}"
      LATENCY: "${LATENCY}"
      CRON_SCHEDULE: "${CRON_SCHEDULE}"
      STARTING_BLOCK: "${STARTING_BLOCK}"
      # Chain-Link
      CHAINLINK_SUBSCRIPTION_ID: "${CHAINLINK_SUBSCRIPTION_ID}"
      # Contracts
      CONTRACT_MANAGER_ADDR: "${CONTRACT_MANAGER_ADDR}"
      EXCHANGE_ADDR: "${EXCHANGE_ADDR}"
      EXCHANGE_BINANCE_ADDR: "${EXCHANGE_BINANCE_ADDR}"
      DISPENSER_ADDR: "${DISPENSER_ADDR}"
      # DEV
      LINK_ADDR: "${LINK_ADDR}"
      VRF_ADDR: "${VRF_ADDR}"
    ports:
      - "${PORT_RPC_API}:${PORT_RPC_API}"

  json-api:
    container_name: json-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./microservices/json start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_JSON_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      # CACHE
      REDIS_CACHE_URL: "${REDIS_CACHE_URL}"
      CACHE_TTL: "${CACHE_TTL}"
      CACHE_MAX: "${CACHE_MAX}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      # FE
      PUBLIC_FE_URL: "${JSON_FE_URL}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
    ports:
      # admin-api
      - "${PORT_JSON_API}:${PORT_JSON_API}"

  game-api:
    container_name: game-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./microservices/game start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_GAME_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      GCLOUD_KEYFILE_BASE64_PATH: "${GCLOUD_KEYFILE_BASE64_PATH}"
      PRIVATE_KEY_SECRET_NAME: "${PRIVATE_KEY_SECRET_NAME}"
      # Contracts
      EXCHANGE_ADDR: "${EXCHANGE_ADDR}"
      EXCHANGE_BINANCE_ADDR: "${EXCHANGE_BINANCE_ADDR}"
    ports:
      # game-api
      - "${PORT_GAME_API}:${PORT_GAME_API}"

  cron-api:
    container_name: cron-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./microservices/cron start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_CRON_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_QUEUE_CRON: "${RMQ_QUEUE_CRON}"
      RMQ_QUEUE_CORE_ETH: "${RMQ_QUEUE_CORE_ETH}"
      RMQ_QUEUE_CORE_ETH_BINANCE: "${RMQ_QUEUE_CORE_ETH_BINANCE}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
    ports:
      # cron-api
      - "${PORT_CRON_API}:${PORT_CRON_API}"

  emailer:
    container_name: emailer
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./microservices/eml start:${BASE_MODE}"
    environment:
      # common
      NODE_OPTIONS: --max-old-space-size=8192
      HOST: 0.0.0.0
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_QUEUE_EMAIL: email
      # mailjet
      MAILJET_PUBLIC_KEY: "${MAILJET_PUBLIC_KEY}"
      MAILJET_PRIVATE_KEY: "${MAILJET_PRIVATE_KEY}"
      MAILJET_FROM: "${MAILJET_FROM}"
      # logDNA
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
    ports:
      # emailer
      - "${PORT_EML_API}:${PORT_EML_API}"


  signal-api:
    container_name: signal-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./microservices/signal start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_SIGNAL_API}"
      # CORS URLS
      ADMIN_FE_URL_B2B: "${ADMIN_FE_URL}"
      ADMIN_FE_URL_B2C: "${ADMIN_FE_URL}"
      MARKET_FE_URL_B2B: "${MARKET_FE_URL}"
      MARKET_FE_URL_B2C: "${MARKET_FE_URL}"
      OFFICE_FE_URL: "${OFFICE_FE_URL}"
      PUBLIC_FE_URL: "${ADMIN_FE_URL}"
      # admin socket io
      SIGNAL_FE_URL: "${SIGNAL_FE_URL}"
      ADMIN_IO_PASSWORD_HASH: "${ADMIN_IO_PASSWORD_HASH}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_WS_URL: "${REDIS_WS_URL}"
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_QUEUE_SIGNAL: "${RMQ_QUEUE_SIGNAL}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
    volumes:
      - static-signal-ui:/home/node/framework/node_modules/@socket.io/admin-ui/ui/dist/
    ports:
      # signal-api
      - "${PORT_SIGNAL_API}:${PORT_SIGNAL_API}"

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/admin.${BASE_MODE}.conf:/etc/nginx/conf.d/admin.conf
      - ./nginx/log:/var/log/nginx/
      - type: volume
        source: static-admin-ui
        target: /var/www/admin-ui/static
        volume:
          nocopy: true
      - type: volume
        source: static-market-ui
        target: /var/www/market-ui/static
        volume:
          nocopy: true
      - type: volume
        source: static-office-ui
        target: /var/www/office-ui/static
        volume:
          nocopy: true
      - type: volume
        source: static-signal-ui
        target: /var/www/signal-ui/static
        volume:
          nocopy: true
    ports:
      - "80:80"
      - "443:443"
      - "1337:1337"
    depends_on:
      - admin-api
      - market-api
      - office-api
      - json-api
      - game-api
      - cron-api
      - core-eth
      - signal-api